version: '2.0'
services:
    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
